spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: event_service
          uri: lb://EventService
          predicates:
            - Path=/api/events/**

        - id: user_service
          uri: lb://UserService
          predicates:
            - Path=/api/users/**

        - id: payment_service
          uri: lb://PaymentService
          predicates:
            - Path=/api/payments/**

      default-filters:
        - name: AddRequestHeader
          args:
            name: X-Request-Foo
            value: Bar
